echo "Cleaning repo first.."
rm -rf dist
rm -rf build
rm -rf pypiplot.egg-info
rm -rf __pycache__
rm -rf .pytest_cache
rm -rf pypiplot/__pycache__
rm -rf pypiplot/.pylint.d
rm -rf pypiplot/tests/__pycache__
rm -rf tests/__pycache__
rm -rf pypiplot/utils/__pycache__
rm -rf .pylint.d
rm -rf pypiplot/data/*.zip
rm -rf pypiplot/data/*.csv
rm -rf *.js
rm -rf *.html
rm -rf *.css
rm -rf *.dot
rm -rf *.png
rm -rf .coverage*
rm -rf .pkl
rm -rf pypiplot.egg-info